import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { CartProvider } from "./context/CartContext";
import { Toaster } from 'sonner';
import { AuthProvider } from "./context/AuthContext";
import LayoutWrapper from "@/component/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
        
         <CartProvider>
<LayoutWrapper>
  <main className="grow ">{children}</main>
</LayoutWrapper>
            <Toaster position="top-right" />

         </CartProvider>
         </AuthProvider>
       </body>
    </html>
  );
}
